---
openapi: 3.0.1
info:
  title: Pokedex API V1
  version: v1
paths:
  "/api/v1/pokemons":
    get:
      summary: list all pokemons in the system
      responses:
        "200":
          description: successful
    post:
      summary: Create a single pokemon
      responses:
        "200":
          description: successful
  "/api/v1/pokemons/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: Show a single pokemon
      responses:
        "200":
          description: successful
    put:
      summary: Update a single pokemon
      responses:
        "200":
          description: successful
    delete:
      summary: Delete a single pokemon
      responses:
        "200":
          description: successful
servers:
  - url: http://localhost:3000/
    variables:
      defaultHost:
        default: http://localhost:3000/
